# fly.toml app configuration file generated for kapansolat on 2024-07-29T22:11:51Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'kapansolat'
primary_region = 'sin'

[build]
  [build.args]
    GO_VERSION = '1.22.2'

[env]
  APP_PORT = '3000'

[http_service]
  internal_port = 3000
  force_https = false
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
